name: zenml server config

on:
  push:
    branches:
      - main

jobs:
  zenml-build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Run Docker Compose
      working-directory: zenml_config
      run: docker-compose -f zenml_conf.yml up --build -d
